package:
    name: tedp

  {% if GIT_DESCRIBE_NUMBER|int == 0 %}
    version: {{GIT_DESCRIBE_TAG}}
  {% else %}
    # If we're using a non-tagged revision, append '.postN' to the version
    version: {{GIT_DESCRIBE_TAG}}.post{{GIT_DESCRIBE_NUMBER}}
  {% endif %}
  
source:
  path: ../

build:
  number: 1

  #
  # You must build this recipe using 'conda build --python=X.Y --numpy=X.Y'
  #
  string: np{{CONDA_NPY}}py{{CONDA_PY}}_{{PKG_BUILDNUM}}_g{{GIT_FULL_HASH[:7]}}
  
  script_env:
    - SKIP_TED_TESTS
  
requirements:
  build:
    - cmake
    - boost 1.63.0
    - jpeg 9*
    - libpng 1.6.28
    - vigra 1.11*
    - boost 1.63.0
    - h5py 
    - hdf5        1.8.18
    - python >=2.7
    - python {{PY_VER}}*
    - numpy >=1.9,{{NPY_VER}}*
    
  run:
    - boost 1.63.0
    - hdf5        1.8.18
    - jpeg 9*
    - vigra 1.11*
    - libpng >=1.6.28,<1.7  # On Mac, libpng versions are not backwards compatible, unfortunately.
                            # See: https://github.com/conda-forge/libpng-feedstock/issues/10
    - python {{PY_VER}}*
    - numpy  {{NPY_VER}}*

test:
  # Python imports
  imports:
    - pyted

about:
  home: http://github.com/stephenplaza/ted
